# -*- coding: utf-8 -*-
# Generated by Django 1.10a1 on 2016-07-04 05:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import em16.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('teamHomeAlias', models.CharField(max_length=50, null=True, verbose_name='Heimteam Liste')),
                ('teamGuestAlias', models.CharField(max_length=50, null=True, verbose_name='Gastteam Liste')),
                ('teamHomeGoals', models.PositiveIntegerField(blank=True, null=True)),
                ('teamGuestGoals', models.PositiveIntegerField(blank=True, null=True)),
                ('others', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'ordering': ['date', 'time'],
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Vorname')),
                ('surname', models.CharField(max_length=100, verbose_name='Nachname')),
                ('position', models.CharField(choices=[('Torwart', 'Torwart'), ('Stürmer', 'Stürmer'), ('Mittelfeld', 'Mittelfeld'), ('Verteidigung', 'Verteidigung')], default='--', max_length=20, verbose_name='Position')),
                ('number', models.IntegerField(default=0, verbose_name='Nummer')),
                ('img', models.ImageField(upload_to=em16.models.upload_to_dir_player, verbose_name='Spielerbild')),
            ],
            options={
                'ordering': ['surname'],
            },
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Stadium',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('capacity', models.IntegerField()),
            ],
            options={
                'ordering': ['city'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=50, unique=True, verbose_name='Team')),
                ('short', models.CharField(default='', max_length=3)),
                ('trainer', models.CharField(max_length=100)),
                ('flag', models.ImageField(default='', upload_to=em16.models.upload_to_dir, verbose_name='Nationalflagge')),
                ('games_played', models.PositiveIntegerField(default=0)),
                ('win', models.PositiveIntegerField(default=0)),
                ('draw', models.PositiveIntegerField(default=0)),
                ('lost', models.PositiveIntegerField(default=0)),
                ('goal', models.PositiveIntegerField(default=0)),
                ('goal_conceded', models.PositiveIntegerField(default=0)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group', to='em16.Group', verbose_name='Gruppe')),
            ],
            options={
                'ordering': ['country'],
            },
        ),
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team', to='em16.Team', verbose_name='Nationalmannschaft'),
        ),
        migrations.AddField(
            model_name='game',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='em16.Group'),
        ),
        migrations.AddField(
            model_name='game',
            name='host',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='stadiums', to='em16.Stadium', verbose_name='Gastgeber'),
        ),
        migrations.AddField(
            model_name='game',
            name='round',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='em16.Round'),
        ),
        migrations.AddField(
            model_name='game',
            name='teamGuest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guest', to='em16.Team'),
        ),
        migrations.AddField(
            model_name='game',
            name='teamHome',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home', to='em16.Team'),
        ),
    ]
