# -*- coding: utf-8 -*-
# Generated by Django 1.10a1 on 2016-07-04 05:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('em16', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ['name']},
        ),
        migrations.RenameField(
            model_name='team',
            old_name='country',
            new_name='name',
        ),
        migrations.AddField(
            model_name='team',
            name='groupAlias',
            field=models.CharField(default='', max_length=2, unique=True),
        ),
    ]
