# -*- coding: utf-8 -*-
# Generated by Django 1.10a1 on 2016-07-04 07:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('em16', '0002_auto_20160704_0747'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='groupAlias',
        ),
    ]
